name: Update Cache 

on:
  workflow_dispatch: 

jobs:
  playwright-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

        # setup node
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

        # caching: package builds
      - name: Cache Playwright binaries
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright
          restore-keys: ${{ runner.os }}-playwright

      # this should still respect the cached binary files for playwright but also just "install" them
      - name: Installing Playwright
        run: npx playwright install --with-deps 
        
