name: Publish Packages to npmjs

on:
  release:
    types: [published]
  workflow_dispatch:  # Allows manual triggering
    inputs:
      force_build:
        description: 'Force build?'
        required: false
        default: false
        type: boolean 
jobs:
  initialise:
    uses: ./.github/workflows/initialise.yml
    with:
      force_build: ${{ github.event.inputs.force_build  || false }}

  publish:
    runs-on: ubuntu-latest
    needs: initialise
    steps:
      - uses: actions/checkout@v4

        # setup node
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

        # caching: node_modules
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-modules
          restore-keys: ${{ runner.os }}-modules

        # caching: package builds
      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: packages/**/lib
          key: ${{ runner.os }}-build
          restore-keys: ${{ runner.os }}-build

        # Publish to npm
      - name: Publish to npmjs.com
        run: npm run publish -- --ci --verbose
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          CI: true 
          
