name: Tests

on:
  pull_request:
    branches: [ main, master ]

jobs:
  initialise:
    if: "!contains(github.event.pull_request.title, 'wip:')"
    uses: ./.github/workflows/initialise.yml
    with:
      force_build: ${{ github.event.inputs.force_build  || false }}

  test:
    needs: initialise
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

        # setup node
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

        # caching: node_modules
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-modules
          restore-keys: ${{ runner.os }}-modules

        # caching: package builds
      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: packages/**/lib
          key: ${{ runner.os }}-build
          restore-keys: ${{ runner.os }}-build

        # caching: package builds
      - name: Cache Playwright binaries
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright
          restore-keys: ${{ runner.os }}-playwright

      # this should still respect the cached binary files for playwright but also just "install" them
      - name: Installing Playwright
        run: npx playwright install --with-deps 
        
      - name: Conditionally Update Screenshots
        if: ${{ github.event.inputs.update_snapshots == 'true' }}
        run: npm test -- --update-snapshots

        # Run tests
      - name: Running Tests 
        run: npm test

      - name: Upload Playwright artifacts
        if: failure()
        # continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          overwrite: true  # Allow overwriting of artifacts with the same name
          path: |
            ./packages/**/*/tests/test-results
            ./packages/**/*/tests/snapshots
          retention-days: 3  # Optional: specify how long to keep artifacts